# Generated by Django 3.2.8 on 2022-07-22 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ilab', '0003_auto_20220722_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javascript',
            name='id',
            field=models.UUIDField(default=uuid.UUID('58d42fa2-3dd1-4c84-bad5-12412bd583ce'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='javascript',
            name='interpreter_path',
            field=models.CharField(default='/Users/king_ahmed1421/Simba/Ployem/backend/ilab/models/interpreters/58d42fa2-3dd1-4c84-bad5-12412bd583ce.js', max_length=676),
        ),
        migrations.AlterField(
            model_name='python',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ec2669ca-397f-4f49-ab40-a2a4c77955f2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='python',
            name='interpreter_path',
            field=models.CharField(default='/Users/king_ahmed1421/Simba/Ployem/backend/ilab/models/interpreters/ec2669ca-397f-4f49-ab40-a2a4c77955f2.py', max_length=676),
        ),
    ]
