# Generated by Django 3.2.8 on 2022-07-22 20:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ilab', '0004_auto_20220722_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javascript',
            name='id',
            field=models.UUIDField(default=uuid.UUID('37307646-d143-4e20-be86-1bb2a045185d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='javascript',
            name='interpreter_path',
            field=models.CharField(default='/Users/king_ahmed1421/Simba/Ployem/backend/ilab/models/interpreters/37307646-d143-4e20-be86-1bb2a045185d.js', max_length=676),
        ),
        migrations.AlterField(
            model_name='python',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1730e784-7d50-4851-8a86-da30f06fe361'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='python',
            name='interpreter_path',
            field=models.CharField(default='/Users/king_ahmed1421/Simba/Ployem/backend/ilab/models/interpreters/1730e784-7d50-4851-8a86-da30f06fe361.py', max_length=676),
        ),
    ]
